import type { Category, Product } from './types';

// Generated from https://faiza.kg/menu public API
export const MENU_CATEGORIES: Category[] = [
  "Горячие блюда",
  "Холодные блюда",
  "Салаты",
  "Шашлык",
  "Гарниры",
  "Напитки"
];

export const MENU_ITEMS: Product[] = [
  {
    id: 'faiza-53',
    name: 'Босо Лагман',
    description: 'Лагман является популярным блюдом среднеазиатской кухни. Готовится из тянутой лапши, мяса и овощей. Лапша растягивается вручную. Также в лагман добавляются пряности и зелень. Подается в горячем виде. Босо — это вид лагмана, являющийся жареным.',
    category: 'Горячие блюда',
    price: 390,
    prepTimeMin: 10,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4288.jpg',
    options: [
      { id: '53-1', grams: 250, price: 390 },
      { id: '53-2', grams: 160, price: 270 },
    ],
  },
  {
    id: 'faiza-51',
    name: 'Гюро Ганфан',
    description: 'Ган-фан по способу приготовления имеет сходства с лагманом, но здесь в качестве гарнира используется не лапша, а отварной рис. Для придания аромата добавляются овощи и специи. Подается в горячем виде. Гюро — означает, что подлив является не жидким, а густым.',
    category: 'Горячие блюда',
    price: 380,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4271_qVNIYNp.jpg',
    options: [
      { id: '51-1', grams: 250, price: 380 },
      { id: '51-2', grams: 180, price: 260 },
    ],
  },
  {
    id: 'faiza-50',
    name: 'Гюро Лагман',
    description: 'Лагман является популярным блюдом среднеазиатской кухни. Готовится из тянутой лапши, мяса и овощей. Лапша растягивается вручную. Также в лагман добавляются пряности и зелень. Подается в горячем виде. Гюро — означает, что подлив является не жидким, а густым.',
    category: 'Горячие блюда',
    price: 380,
    prepTimeMin: 10,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4272.jpg',
    options: [
      { id: '50-1', grams: 250, price: 380 },
      { id: '50-2', grams: 180, price: 260 },
    ],
  },
  {
    id: 'faiza-49',
    name: 'Лагман',
    description: 'Лагман является популярным блюдом среднеазиатской кухни. Готовится из тянутой лапши, мяса и овощей. Лапша растягивается вручную. Также в лагман добавляются пряности и зелень. Подается в горячем виде.',
    category: 'Горячие блюда',
    price: 340,
    prepTimeMin: 10,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4267.jpg',
    options: [
      { id: '49-1', grams: 250, price: 340 },
      { id: '49-2', grams: 180, price: 240 },
    ],
  },
  {
    id: 'faiza-48',
    name: 'Гюро Ганфан',
    description: 'Ган-фан по способу приготовления имеет сходства с лагманом, но здесь в качестве гарнира используется не лапша, а отварной рис. Для придания аромата добавляются овощи и специи. Подается в горячем виде. Гюро — означает, что подлив является не жидким, а густым.',
    category: 'Горячие блюда',
    price: 380,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4271.jpg',
    options: [
      { id: '48-1', grams: 320, price: 380 },
      { id: '48-2', grams: 250, price: 260 },
    ],
  },
  {
    id: 'faiza-47',
    name: 'Ган-фан',
    description: 'Ган-фан по способу приготовления имеет сходства с лагманом, но здесь в качестве гарнира используется не лапша, а отварной рис. Для придания аромата добавляются овощи и специи. Подается в горячем виде.',
    category: 'Горячие блюда',
    price: 340,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4268.jpg',
    options: [
      { id: '47-1', grams: 250, price: 340 },
      { id: '47-2', grams: 180, price: 240 },
    ],
  },
  {
    id: 'faiza-45',
    name: 'Мампар',
    description: 'Мампар — это блюдо восточной кухни, которое готовится из мелких галушек, сделанных из теста. Является разновидностью супа. Галушки заливаются бульоном с добавлением овощей и специй.',
    category: 'Горячие блюда',
    price: 300,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4326.jpg',
    options: [
      { id: '45-1', grams: 250, price: 300 },
      { id: '45-2', grams: 180, price: 210 },
    ],
  },
  {
    id: 'faiza-46',
    name: 'Шорпо',
    description: 'Шорпо — это мясной бульон с мясом и картофелем, который готовят все народы Средней Азии. Является очень жирным и питательным блюдом. Для придания особого аромата добавляются лук и специи.',
    category: 'Горячие блюда',
    price: 280,
    prepTimeMin: 10,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4343.jpg',
    options: [
      { id: '46-1', grams: 250, price: 280 },
      { id: '46-2', grams: 180, price: 190 },
    ],
  },
  {
    id: 'faiza-44',
    name: 'Чучвара',
    description: 'Чучвара — это  блюдо, приготовленное в виде отварных изделий из теста с мясной начинкой. Является разновидностью пельменей, но значительно меньше по размеру. В качетсве соуса можно использовать сметану или кетчуп.',
    category: 'Горячие блюда',
    price: 300,
    prepTimeMin: 10,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4349.jpg',
    options: [
      { id: '44-1', grams: 250, price: 300 },
      { id: '44-2', grams: 180, price: 210 },
    ],
  },
  {
    id: 'faiza-43',
    name: 'Борщ',
    description: 'Борщ — это разновидность супа. Является национальным блюдом у многих народов. Готовится из капусты и свеклы, которая придает блюду насыщенный красный цвет. Борщ является очень сытным блюдом. Идеален в сочетании со сметаной.',
    category: 'Горячие блюда',
    price: 260,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4344.jpg',
    options: [
      { id: '43-1', grams: 250, price: 260 },
      { id: '43-2', grams: 180, price: 170 },
    ],
  },
  {
    id: 'faiza-42',
    name: 'Пельмени со сметаной',
    description: 'Распространенное блюдо из теста с начинкой из рубленого мяса. Также в дополнение к мясу добавляется лук и специи. В качестве соуса предлагаем попробовать сметану, которая придает пельменям приятный сливочный аромат и нежный вкус.',
    category: 'Горячие блюда',
    price: 300,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4339.jpg',
    options: [
      { id: '42-1', grams: 250, price: 300 },
      { id: '42-2', grams: 180, price: 210 },
    ],
  },
  {
    id: 'faiza-41',
    name: 'Плов (узгенский рис)',
    description: 'Знаменитый плов из узгенского риса — блюдо из риса и мяса, которые готовятся одновременно. Очень большое значение при приготовлении плова придается рису и его вкусу. Каждое зернышко должно отделяться от других. Для приятного аромата добавляется чеснок.',
    category: 'Горячие блюда',
    price: 350,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_1363.jpg',
    options: [
      { id: '41-1', grams: 250, price: 350 },
      { id: '41-2', grams: 180, price: 260 },
    ],
  },
  {
    id: 'faiza-40',
    name: 'Плов (рис лазер)',
    description: 'Плов приготовлен на основе риса «Лазер» — блюдо из риса и мяса, которые готовятся одновременно. Очень большое значение при приготовлении плова придается рису и его вкусу. Каждое зернышко должно отделяться от других. Для приятного аромата добавляется горох «нут».',
    category: 'Горячие блюда',
    price: 350,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4309.jpg',
    options: [
      { id: '40-1', grams: 250, price: 350 },
      { id: '40-2', grams: 180, price: 260 },
    ],
  },
  {
    id: 'faiza-39',
    name: 'Манты с мясом',
    description: 'Манты являются традиционным мясным блюдом народов Центральной Азии. Готовятся из мелко нарубленного мяса и лука в тонко раскатанном тесте. Готовятся на пару.',
    category: 'Горячие блюда',
    price: 350,
    prepTimeMin: 10,
    imageUrl: 'https://faiza.kg/media/menu/dishes/8D762D3A-48B0-4574-B311-02F36438230F.jpeg',
    options: [
      { id: '39-1', grams: 5, price: 350 },
      { id: '39-2', grams: 1, price: 70 },
    ],
  },
  {
    id: 'faiza-37',
    name: 'Манты жареные',
    description: 'Манты являются традиционным мясным блюдом народов Центральной Азии. Готовятся из мелко нарубленного мяса и лука в тонко раскатанном тесте. Готовятся на пару. Данный вариант мант после приготовления также обжаривается, что дает блюду вкусную хрустящую корочку.',
    category: 'Горячие блюда',
    price: 375,
    prepTimeMin: 10,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4293_Eyy9L78.jpg',
    options: [
      { id: '37-1', grams: 5, price: 375 },
      { id: '37-2', grams: 1, price: 75 },
    ],
  },
  {
    id: 'faiza-35',
    name: 'Жаренные пельмени',
    description: 'Распространенное блюдо из теста с начинкой из рубленого мяса. Также в дополнение к мясу добавляется лук и специи. В данном варианте подаются пельмени, поджаренные на сковороде, которые имеют хрустящую корочку.',
    category: 'Горячие блюда',
    price: 320,
    prepTimeMin: 10,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4317.jpg',
    options: [
      { id: '35-1', grams: 200, price: 320 },
      { id: '35-2', grams: 140, price: 230 },
    ],
  },
  {
    id: 'faiza-34',
    name: 'Бифштекс с яйцом и пюре',
    description: 'Блюдо, приготовленное из жареной говядины. Готовится из сочной вырезки. Является одним из самых популярных в мире блюд. Мясо отлично прожарено и имеет нежный вкус. Подается с гарниром из картофельного пюре.',
    category: 'Горячие блюда',
    price: 380,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4384.jpg',
    options: [
      { id: '34-1', grams: 220, price: 380 },
    ],
  },
  {
    id: 'faiza-33',
    name: 'Бифштекс с яйцом и рисом',
    description: 'Блюдо, приготовленное из жареной говядины. Готовится из сочной вырезки. Является одним из самых популярных в мире блюд. Мясо отлично прожарено и имеет нежный вкус. Подается с гарниром из отваренного риса.',
    category: 'Горячие блюда',
    price: 380,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4380.jpg',
    options: [
      { id: '33-1', grams: 220, price: 380 },
    ],
  },
  {
    id: 'faiza-32',
    name: 'Бифштекс с яйцом и гречкой',
    description: 'Блюдо, приготовленное из жареной говядины. Готовится из сочной вырезки. Является одним из самых популярных в мире блюд. Мясо отлично прожарено и имеет нежный вкус. Подается с гарниром из отваренной гречки.',
    category: 'Горячие блюда',
    price: 380,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4378.jpg',
    options: [
      { id: '32-1', grams: 220, price: 380 },
    ],
  },
  {
    id: 'faiza-31',
    name: 'Бифштекс с яйцом и сложным гарниром',
    description: 'Блюдо, приготовленное из жареной говядины. Готовится из сочной вырезки. Является одним из самых популярных в мире блюд. Мясо отлично прожарено и имеет нежный вкус. Подается со сложным гарниром из риса, картошки пюре и гречки.',
    category: 'Горячие блюда',
    price: 380,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4375.jpg',
    options: [
      { id: '31-1', grams: 220, price: 380 },
    ],
  },
  {
    id: 'faiza-30',
    name: 'Бифштекс с яйцом',
    description: 'Блюдо, приготовленное из жареной говядины. Готовится из сочной вырезки. Является одним из самых популярных в мире блюд. Мясо отлично прожарено и имеет нежный вкус.',
    category: 'Горячие блюда',
    price: 260,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_1392.jpg',
    options: [
      { id: '30-1', grams: 160, price: 260 },
    ],
  },
  {
    id: 'faiza-29',
    name: 'Бифштекс без яйца с гречкой',
    description: 'Блюдо, приготовленное из жареной говядины. Готовится из сочной вырезки. Является одним из самых популярных в мире блюд. Мясо отлично прожарено и имеет нежный вкус. Подается с гарниром из отваренной гречки.',
    category: 'Горячие блюда',
    price: 330,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4374.jpg',
    options: [
      { id: '29-1', grams: 200, price: 330 },
    ],
  },
  {
    id: 'faiza-28',
    name: 'Бифштекс без яйца с фри',
    description: 'Блюдо, приготовленное из жареной говядины. Готовится из сочной вырезки. Является одним из самых популярных в мире блюд. Мясо отлично прожарено и имеет нежный вкус. Фри картошкасы менен берилет.',
    category: 'Горячие блюда',
    price: 330,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4381_QBoQi8x.jpg',
    options: [
      { id: '28-1', grams: 195, price: 330 },
    ],
  },
  {
    id: 'faiza-27',
    name: 'Бифштекс без яйца с пюре',
    description: 'Блюдо, приготовленное из жареной говядины. Готовится из сочной вырезки. Является одним из самых популярных в мире блюд. Мясо отлично прожарено и имеет нежный вкус. Подается с гарниром из картофельного пюре.',
    category: 'Горячие блюда',
    price: 330,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4381.jpg',
    options: [
      { id: '27-1', grams: 220, price: 330 },
    ],
  },
  {
    id: 'faiza-26',
    name: 'Бифштекс',
    description: 'Блюдо, приготовленное из жареной говядины. Готовится из сочной вырезки. Является одним из самых популярных в мире блюд. Мясо отлично прожарено и имеет нежный вкус.',
    category: 'Горячие блюда',
    price: 210,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_1383.jpg',
    options: [
      { id: '26-1', grams: 100, price: 210 },
    ],
  },
  {
    id: 'faiza-25',
    name: 'Бефстроганов с гречкой',
    description: 'Бефстроганов — популярное блюдо, которое приготовлено из мелко нарезанных кусочков говядины. Блюдо заливается вкусным соусом. Подается свежеприготовленным и горячим. Подается с гарниром из отваренной гречки.',
    category: 'Горячие блюда',
    price: 420,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4357.jpg',
    options: [
      { id: '25-1', grams: 220, price: 420 },
      { id: '25-2', grams: 120, price: 310 },
    ],
  },
  {
    id: 'faiza-24',
    name: 'Бефстроганов с пюре',
    description: 'Бефстроганов — популярное блюдо, которое приготовлено из мелко нарезанных кусочков говядины. Блюдо заливается вкусным соусом. Подается свежеприготовленным и горячим. Подается с гарниром из картофельного пюре.',
    category: 'Горячие блюда',
    price: 420,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4356.jpg',
    options: [
      { id: '24-1', grams: 220, price: 420 },
      { id: '24-2', grams: 120, price: 310 },
    ],
  },
  {
    id: 'faiza-23',
    name: 'Бефстроганов с рисом',
    description: 'Бефстроганов — популярное блюдо, которое приготовлено из мелко нарезанных кусочков говядины. Блюдо заливается вкусным соусом. Подается свежеприготовленным и горячим. Подается с гарниром из отваренного риса.',
    category: 'Горячие блюда',
    price: 420,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4368_reZG6AQ.jpg',
    options: [
      { id: '23-1', grams: 220, price: 420 },
      { id: '23-2', grams: 120, price: 310 },
    ],
  },
  {
    id: 'faiza-22',
    name: 'Бефстроганов со сложный гарнир',
    description: 'Бефстроганов — популярное блюдо, которое приготовлено из мелко нарезанных кусочков говядины. Блюдо заливается вкусным соусом. Подается свежеприготовленным и горячим. Подается со сложным гарниром из риса, картошки пюре и гречки.',
    category: 'Горячие блюда',
    price: 420,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_1379.jpg',
    options: [
      { id: '22-1', grams: 270, price: 420 },
      { id: '22-2', grams: 200, price: 310 },
    ],
  },
  {
    id: 'faiza-21',
    name: 'Бефстроганов с фри',
    description: 'Бефстроганов — популярное блюдо, которое приготовлено из мелко нарезанных кусочков говядины. Блюдо заливается вкусным соусом. Подается свежеприготовленным и горячим. Подается с гарниром из картошки фри.',
    category: 'Горячие блюда',
    price: 420,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4361.jpg',
    options: [
      { id: '21-1', grams: 220, price: 420 },
      { id: '21-2', grams: 120, price: 310 },
    ],
  },
  {
    id: 'faiza-20',
    name: 'Бефстроганов',
    description: 'Бефстроганов — популярное блюдо, которое приготовлено из мелко нарезанных кусочков говядины. Блюдо заливается вкусным соусом. Подается свежеприготовленным и горячим.',
    category: 'Горячие блюда',
    price: 300,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_1362.jpg',
    options: [
      { id: '20-1', grams: 220, price: 300 },
      { id: '20-2', grams: 120, price: 250 },
    ],
  },
  {
    id: 'faiza-19',
    name: 'Гуляш с пюре',
    description: 'Блюдо из кусочков мяса, которые тушатся с луком, перцем и картофелем. Относится к категории густых супов. От долгого тушения появляется ароматный соус. Гуляш подается с гарниром из картофельного пюре.',
    category: 'Горячие блюда',
    price: 420,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_1386_BGfEuEp.jpg',
    options: [
      { id: '19-1', grams: 220, price: 420 },
      { id: '19-2', grams: 120, price: 310 },
    ],
  },
  {
    id: 'faiza-18',
    name: 'Гуляш с рисом',
    description: 'Блюдо из кусочков мяса, которые тушатся с луком, перцем и картофелем. Относится к категории густых супов. От долгого тушения появляется ароматный соус. Гуляш подается с гарниром из отваренного риса.',
    category: 'Горячие блюда',
    price: 420,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4368.jpg',
    options: [
      { id: '18-1', grams: 220, price: 420 },
      { id: '18-2', grams: 120, price: 310 },
    ],
  },
  {
    id: 'faiza-17',
    name: 'Гуляш с гречкой',
    description: 'Блюдо из кусочков мяса, которые тушатся с луком, перцем и картофелем. Относится к категории густых супов. От долгого тушения появляется ароматный соус. Гуляш подается с гарниром из гречки.',
    category: 'Горячие блюда',
    price: 420,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4369.jpg',
    options: [
      { id: '17-1', grams: 220, price: 420 },
      { id: '17-2', grams: 120, price: 310 },
    ],
  },
  {
    id: 'faiza-16',
    name: 'Гуляш со сложным гарниром',
    description: 'Блюдо из кусочков мяса, которые тушатся с луком, перцем и картофелем. Относится к категории густых супов. От долгого тушения появляется ароматный соус. Подается со сложным гарниром.',
    category: 'Горячие блюда',
    price: 420,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4364.jpg',
    options: [
      { id: '16-1', grams: 220, price: 420 },
      { id: '16-2', grams: 120, price: 310 },
    ],
  },
  {
    id: 'faiza-15',
    name: 'Гуляш без гарнира',
    description: 'Блюдо из кусочков мяса, которые тушатся с луком, перцем и картофелем. Относится к категории густых супов. От долгого тушения появляется ароматный соус.',
    category: 'Горячие блюда',
    price: 300,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_1356.jpg',
    options: [
      { id: '15-1', grams: 200, price: 300 },
      { id: '15-2', grams: 180, price: 250 },
    ],
  },
  {
    id: 'faiza-14',
    name: 'Котлета в кляре c пюре',
    description: 'Котлета из рубленной говядины с гарниром из картофельного пюре',
    category: 'Горячие блюда',
    price: 360,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4386.jpg',
    options: [
      { id: '14-1', grams: 220, price: 360 },
    ],
  },
  {
    id: 'faiza-13',
    name: 'Котлета в кляре с гречкой',
    description: 'Котлета из рубленной говядины в яичном кляре подается с гарниром из отваренной гречки',
    category: 'Горячие блюда',
    price: 360,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4396.jpg',
    options: [
      { id: '13-1', grams: 220, price: 360 },
    ],
  },
  {
    id: 'faiza-12',
    name: 'Котлета в кляре с рисом',
    description: 'Chopped beef cutlet in egg batter served with boiled rice.',
    category: 'Горячие блюда',
    price: 360,
    prepTimeMin: 10,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4389.jpg',
    options: [
      { id: '12-1', grams: 220, price: 360 },
    ],
  },
  {
    id: 'faiza-11',
    name: 'Котлета в кляре со сложный гарниром',
    description: 'Котлета в яичном кляре, которая подается со сложным гарниром: Гречка, Пюре, Рис',
    category: 'Горячие блюда',
    price: 360,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4392.jpg',
    options: [
      { id: '11-1', grams: 220, price: 360 },
    ],
  },
  {
    id: 'faiza-10',
    name: 'Котлета в кляре без гарнира',
    description: 'Котлета в яичном кляре без гарнира',
    category: 'Горячие блюда',
    price: 240,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_1395.jpg',
    options: [
      { id: '10-1', grams: 150, price: 240 },
    ],
  },
  {
    id: 'faiza-9',
    name: 'Котлета в кляре с фри',
    description: 'Вкусная сочная котлета в яичном кляре. Подается с картошкой фри.',
    category: 'Горячие блюда',
    price: 360,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4397.jpg',
    options: [
      { id: '9-1', grams: 170, price: 360 },
    ],
  },
  {
    id: 'faiza-8',
    name: 'Яичница-глазунья',
    description: 'Традиционный вкусный, стыный и полезный завтрак',
    category: 'Горячие блюда',
    price: 100,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4398.jpg',
    options: [
      { id: '8-1', grams: 2, price: 100 },
      { id: '8-2', grams: 1, price: 50 },
    ],
  },
  {
    id: 'faiza-7',
    name: 'Гуляш (+гарнир)',
    description: 'Блюдо из кусочков мяса, которые тушатся с луком, перцем и картофелем. Относится к категории густых супов. От долгого тушения появляется ароматный соус. Гуляш принято подавать с гарниром.',
    category: 'Горячие блюда',
    price: 420,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_1386.jpg',
    options: [
      { id: '7-1', grams: 220, price: 420 },
    ],
  },
  {
    id: 'faiza-6',
    name: 'Самсы',
    description: 'Самса — традиционное мучное изделие восточной кухни. Готовится в виде треугольников с начинкой из рубленого мяса с луком. Используется слоеное тесто. Подаются в горячем виде.',
    category: 'Горячие блюда',
    price: 100,
    prepTimeMin: 10,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4297.jpg',
    options: [
      { id: '6-1', grams: 1, price: 100 },
    ],
  },
  {
    id: 'faiza-5',
    name: 'Гош-нан',
    description: 'Среднеазиатское блюдо гош-нан представляет собой лепешку с мясной начинкой. Добавление лука и специй делаю гош-нан ароматнее и вкуснее.',
    category: 'Горячие блюда',
    price: 340,
    prepTimeMin: 10,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4294.jpg',
    options: [
      { id: '5-1', grams: 1, price: 340 },
    ],
  },
  {
    id: 'faiza-59',
    name: 'Ашлям-Фу',
    description: 'Блюдо уйгурской и дунганской кухни, которое готовится во многих азиатских странах, но самым вкусным заслуженно признано ашлям-фу, которое готовят в Кыргызстане. Готовится из крахмала с остро-кислым овощным соусом. Подается в холодном виде.',
    category: 'Холодные блюда',
    price: 240,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4329.jpg',
    options: [
      { id: '59-1', grams: 250, price: 240 },
      { id: '59-2', grams: 180, price: 170 },
    ],
  },
  {
    id: 'faiza-58',
    name: 'Окрошка',
    description: 'Окрошка — это традиционное блюдо русской кухни. Представляет собой холодный суп из мелко нарезанных овощей, мяса и заправленный майонезом. Является очень вкусным и питательным блюдом. Особенно хороша окрошка в жаркие периоды.',
    category: 'Холодные блюда',
    price: 260,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4336.jpg',
    options: [
      { id: '58-1', grams: 250, price: 260 },
      { id: '58-2', grams: 180, price: 190 },
    ],
  },
  {
    id: 'faiza-57',
    name: 'Блины со сгущенкой',
    description: 'Блины — жареное кулинарное изделие, которое готовится из очень жидкого теста, которое разливается по раскаленной сковороде. Блины подаются с самыми разнообразными закусками. В данном варианте дополнением к блинам является сгущенное молоко.',
    category: 'Холодные блюда',
    price: 165,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4224.jpg',
    options: [
      { id: '57-1', grams: 3, price: 165 },
    ],
  },
  {
    id: 'faiza-56',
    name: 'Блины со сметаной',
    description: 'Блины — жареное кулинарное изделие, которое готовится из очень жидкого теста, которое разливается по раскаленной сковороде. Блины подаются с самыми разнообразными закусками. В данном варианте дополнением к блинам является сметана.',
    category: 'Холодные блюда',
    price: 165,
    prepTimeMin: 10,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4225.jpg',
    options: [
      { id: '56-1', grams: 3, price: 165 },
    ],
  },
  {
    id: 'faiza-55',
    name: 'Блины с медом',
    description: 'Блины — жареное кулинарное изделие, которое готовится из очень жидкого теста, которое разливается по раскаленной сковороде. Блины подаются с самыми разнообразными закусками. В данном варианте дополнением к блинам является мед.',
    category: 'Холодные блюда',
    price: 165,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4223.jpg',
    options: [
      { id: '55-1', grams: 3, price: 165 },
    ],
  },
  {
    id: 'faiza-54',
    name: 'Блины с творогом',
    description: 'Блины — жареное кулинарное изделие, которое готовится из очень жидкого теста, которое разливается по раскаленной сковороде. Блины подаются с самыми разнообразными закусками. В данном варианте дополнением к блинам является свежий творог, который делает блюдо очень сытным.',
    category: 'Холодные блюда',
    price: 195,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4231.jpg',
    options: [
      { id: '54-1', grams: 3, price: 195 },
    ],
  },
  {
    id: 'faiza-72',
    name: 'Салат из свежих овощей',
    description: 'Легкий диетический салат из свежих овощей. В состав салата входят помидоры, огурцы, лук и зелень',
    category: 'Салаты',
    price: 160,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4195.jpg',
    options: [
      { id: '72-1', grams: 150, price: 160 },
    ],
  },
  {
    id: 'faiza-71',
    name: 'Салат из свежих овощей со сметаной',
    description: 'Данный салат приготовлен из свежих огурцов, помидоров и лука. Заправка сметаной делает его вкус очень нежным. Свежий салат идеально подходит для любых блюд, как горячих, так и холодных.',
    category: 'Салаты',
    price: 180,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4197.jpg',
    options: [
      { id: '71-1', grams: 180, price: 180 },
    ],
  },
  {
    id: 'faiza-70',
    name: 'Салат "Шакарап"',
    description: 'Шакарап – это простой, но очень вкусный салат, который идеально подходит к мясным горячим блюдам. Репчатый лук в сочетании с соком свежих спелых помидоров приобретает очень тонкий вкус. Данный салат на Востоке всегда подают к плову, так как его сок прекрасно сочетается с рисом.',
    category: 'Салаты',
    price: 160,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4193.jpg',
    options: [
      { id: '70-1', grams: 150, price: 160 },
    ],
  },
  {
    id: 'faiza-69',
    name: 'Салат из грибов',
    description: 'Грибной салат готовится из свежежаренных грибов. Имеет нежный вкус и приятный аромат. Подается с майонезом, который придает блюду особый сливочный аромат и вкус.',
    category: 'Салаты',
    price: 200,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4201.jpg',
    options: [
      { id: '69-1', grams: 120, price: 200 },
    ],
  },
  {
    id: 'faiza-68',
    name: 'Салат "Винегрет"',
    description: 'По сезону',
    category: 'Салаты',
    price: 160,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4202.jpg',
    options: [
      { id: '68-1', grams: 200, price: 160 },
    ],
  },
  {
    id: 'faiza-67',
    name: 'Салат "Оливье"',
    description: 'Очень популярный салат, который украсит собой не только новогодний стол, но и любое другое застолье. Готовится из отварных овощей, яиц и мяса, нарезанных кубиками и заправленных майонезом. Зеленый горошек и зелень делают вкус более насыщенным.',
    category: 'Салаты',
    price: 200,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4203.jpg',
    options: [
      { id: '67-1', grams: 150, price: 200 },
    ],
  },
  {
    id: 'faiza-66',
    name: 'Салат из фунчозы (лянсай)',
    description: 'Салат из стеклянной лапши (фунчозы) — вкусное блюдо среднеазиатской кухни. Блюдо содержит в себе морковь, мясную вырезку, перец. Добавление специй делает салат пикантным. Подается в холодном виде.',
    category: 'Салаты',
    price: 200,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4189_l4Y3LcW.jpg',
    options: [
      { id: '66-1', grams: 150, price: 200 },
    ],
  },
  {
    id: 'faiza-65',
    name: 'Салат из фунчозы с мясом',
    description: 'Салат из полезной и вкусной лапши, приготовленной из крахмала. Прелесть фунчозы заключается в том, что она отлично впитывает в себя вкус и аромат продуктов, с которыми ее готовят. Данный салат приготовлен из мяса, овощей с добавлением чеснока и специй.',
    category: 'Салаты',
    price: 200,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4189.jpg',
    options: [
      { id: '65-1', grams: 150, price: 200 },
    ],
  },
  {
    id: 'faiza-64',
    name: 'Салат из капусты',
    description: 'Вкусный и сочный салат из нарезанной свежей капусты. Отлично сочетается со всеми мясными блюдами. В салат также добавляется морковь и специи.',
    category: 'Салаты',
    price: 160,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4187.jpg',
    options: [
      { id: '64-1', grams: 120, price: 160 },
    ],
  },
  {
    id: 'faiza-63',
    name: 'Салат из моркови',
    description: 'Популярный салат из мелко натертой моркови. Заправляется маслом с добавлением ароматных специй. Блюдо является очень полезным и приготовлено исключительно из свежей моркови.',
    category: 'Салаты',
    price: 160,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4200.jpg',
    options: [
      { id: '63-1', grams: 120, price: 160 },
    ],
  },
  {
    id: 'faiza-93',
    name: 'Шашлык из баранины',
    description: 'Известное мясное блюдо кавказской, восточной и среднеазиатской кухонь, которое уходит корнями в очень старые времена. Готовится из качественной свежей баранины, предварительно замаринованной. Жарится на углях и подается с свежим нарезанным луком.',
    category: 'Шашлык',
    price: 230,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/DSC_0749.jpg',
    options: [
      { id: '93-1', grams: 90, price: 230 },
    ],
  },
  {
    id: 'faiza-92',
    name: 'Шашлык из курицы',
    description: 'Известное мясное блюдо кавказской, восточной и среднеазиатской кухни, которое уходит корнями в очень старые времена. Готовится из качественного свежего куриного мяса, предварительно замаринованного. Жарится на углях и подается со свежим нарезанным луком.',
    category: 'Шашлык',
    price: 200,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/DSC_0747.jpg',
    options: [
      { id: '92-1', grams: 120, price: 200 },
    ],
  },
  {
    id: 'faiza-91',
    name: 'Шашлык из печени',
    description: 'Известное мясное блюдо кавказской, восточной и среднеазиатской кухни, которое уходит корнями в очень старые времена. Данный вид шашлыка готовится из печени и может приятно разнообразить привычное меню. Готовится очень быстро и к тому же печень имеет множество полезных свойств.',
    category: 'Шашлык',
    price: 200,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/DSC_0751.jpg',
    options: [
      { id: '91-1', grams: 100, price: 200 },
    ],
  },
  {
    id: 'faiza-90',
    name: 'Лепешка',
    description: 'Традиционный хлеб восточной и среднеазиатской кухни. Всегда свежий.',
    category: 'Гарниры',
    price: 50,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_1415.jpg',
    options: [
      { id: '90-1', grams: 1, price: 50 },
      { id: '90-2', grams: 0.5, price: 25 },
    ],
  },
  {
    id: 'faiza-89',
    name: 'Лимон',
    description: 'Свежие лимоны выступают неплохой закуской к чаю, кофе, мясным изделиям, холодным рыбным закускам, шашлыкам. Также, благодаря своему аромату, прекрасно сочетается с шоколадом, медом и пряностями.',
    category: 'Гарниры',
    price: 70,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/limon.jpg',
    options: [
      { id: '89-1', grams: 1, price: 70 },
      { id: '89-2', grams: 0.5, price: 35 },
    ],
  },
  {
    id: 'faiza-88',
    name: 'Мёд',
    description: 'Натуральный горный мёд',
    category: 'Гарниры',
    price: 70,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/honey.jpg',
    options: [
      { id: '88-1', grams: 100, price: 70 },
      { id: '88-2', grams: 50, price: 25 },
    ],
  },
  {
    id: 'faiza-87',
    name: 'Сметана домашняя',
    description: 'Сметана — кисломолочный продукт, который получают из сливок и закваски. Является популярным соусом ко многим мясным блюдам и салатам.',
    category: 'Гарниры',
    price: 70,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_1401.jpg',
    options: [
      { id: '87-1', grams: 100, price: 70 },
    ],
  },
  {
    id: 'faiza-86',
    name: 'Кетчуп',
    description: 'Соус, который готовится из отборных помидоров с добавлением уксуса и ароматных специй. Является прекрасной добавкой к мясным блюдам.',
    category: 'Гарниры',
    price: 35,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_1404.jpg',
    options: [
      { id: '86-1', grams: 50, price: 35 },
    ],
  },
  {
    id: 'faiza-85',
    name: 'Одноразовая посуда',
    description: 'Одноразовая посуда для краткосрочного хранения блюд, сделанная из качественного и экологически чистого пластика. Хорошо держит температуру, достаточно компактна и легка. В ассортименте вилки, ножи, ложки и тарелки.',
    category: 'Гарниры',
    price: 12,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/conten.jpg',
    options: [
      { id: '85-1', grams: 1, price: 12 },
    ],
  },
  {
    id: 'faiza-76',
    name: 'Рис',
    description: 'Рис является прекрасным вариантом легкого, вкусного, полезного и питательного гарнира. Отлично подходит для рыбных и мясных блюд.',
    category: 'Гарниры',
    price: 120,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4407.jpg',
    options: [
      { id: '76-1', grams: 200, price: 120 },
    ],
  },
  {
    id: 'faiza-75',
    name: 'Гречка',
    description: 'Отварная гречневая крупа — отличный гарнир для любого блюда. Сама по себе гречка является очень полезным, богатым белками продуктом. Может выступать и в качестве самостоятельного блюда.',
    category: 'Гарниры',
    price: 120,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4406.jpg',
    options: [
      { id: '75-1', grams: 180, price: 120 },
    ],
  },
  {
    id: 'faiza-74',
    name: 'Картофельное пюре',
    description: 'Картофельное пюре является самым популярным гарниром. Оно отлично сочетается с овощами, любым мясом, рыбой и надолго оставляет ощущение сытости. Для приготовления используется отборный свежий картофель.',
    category: 'Гарниры',
    price: 120,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4409.jpg',
    options: [
      { id: '74-1', grams: 200, price: 120 },
    ],
  },
  {
    id: 'faiza-73',
    name: 'Картофель фри',
    description: 'Картофель обжаренный во фритюре до хрустящей корочки.',
    category: 'Гарниры',
    price: 140,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4403.jpg',
    options: [
      { id: '73-1', grams: 170, price: 140 },
    ],
  },
  {
    id: 'faiza-81',
    name: 'Айран',
    description: 'Кисломолочный напиток, который получают из коровьего молока путем брожения. Кефир — распространенный напиток у многих народов мира. Является очень полезным продуктом для организма, так как содержит большое число полезных веществ. Хорошо сочетается со многими блюдами.',
    category: 'Напитки',
    price: 50,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/kefir.jpg',
    options: [
      { id: '81-1', grams: 0.2, price: 50 },
    ],
  },
  {
    id: 'faiza-80',
    name: '«Coca-Cola», «Fanta», «Sprite»',
    description: 'Популярные во всем мире газированные напитки. Подаются всегда в охлажденном виде и отлично утоляют жажду.',
    category: 'Напитки',
    price: 130,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_1424.jpg',
    options: [
      { id: '80-1', grams: 1, price: 130 },
      { id: '80-2', grams: 0.5, price: 90 },
    ],
  },
  {
    id: 'faiza-79',
    name: 'Минеральная вода «Bonaqua», «Легенда»',
    description: 'Минеральная вода «Bonaqua», «Legend» — это вода из натуральных источников, содержащая множество полезных элементов. Имеет высокую степень очистки. Соответствует всем международным стандартам.',
    category: 'Напитки',
    price: 70,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4426.jpg',
    options: [
      { id: '79-1', grams: 1, price: 70 },
      { id: '79-2', grams: 0.5, price: 50 },
    ],
  },
  {
    id: 'faiza-78',
    name: 'Сок натуральный «Gracio»',
    description: 'Соки «Gracio» — это соки европейского уровня качества, сделанные по самым передовым технологиям. Сохранены все полезные качества фруктов и ягод. На Ваш выбор несколько видов сока.',
    category: 'Напитки',
    price: 230,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_0300.jpeg',
    options: [
      { id: '78-1', grams: 1, price: 230 },
    ],
  },
  {
    id: 'faiza-77',
    name: 'Компот',
    description: 'Компот —  десертный напиток, приготовленный из смеси фруктов и ягод путем их варки. Хорошо утоляет жажду и является отличным дополнением к застолью.',
    category: 'Напитки',
    price: 120,
    prepTimeMin: 14,
    imageUrl: 'https://faiza.kg/media/menu/dishes/IMG_4436.jpg',
    options: [
      { id: '77-1', grams: 1, price: 120 },
      { id: '77-2', grams: 0.5, price: 60 },
    ],
  },
];
